name: sqlformat

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-test-unix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        conf:
          - minimum
          - latest-stable
          - latest-beta
          - latest-nightly
        include:
          - conf: minimum
            toolchain: 1.65.0
          - conf: latest-stable
            toolchain: stable
          - conf: latest-beta
            toolchain: beta
          - conf: latest-nightly
            toolchain: nightly
    steps:
      - uses: actions/checkout@v5
      - name: Install ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy, rustfmt
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry/cache
          key: ${{ runner.os }}-${{ matrix.conf }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.conf }}-cargo-registry-
      - name: Run rustfmt
        if: matrix.toolchain == 'stable'
        run: |
          cargo fmt --all -- --check
      - name: Run clippy
        if: matrix.toolchain == 'stable'
        uses: actions-rs-plus/clippy-check@v2.3.0
        with:
          args: --all -- -D warnings
      # FIXME: criterion and its dependencies require a newer version than 1.65, but it is only used for benchmarks.
      # Is there a way to not have criterion built when we run tests?
      - name: Run cargo check
        if: matrix.toolchain == '1.65.0'
        run: cargo check
      - name: Run tests
        if: matrix.toolchain != '1.65.0'
        run: cargo test
      - name: Build benchmarks
        if: matrix.toolchain == 'stable'
        run: cargo bench --no-run
      - name: Build docs
        run: cargo doc --no-deps
